root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  quick-start-10-minutes-or-less: quickstart.md
  setup/adding-s3-bucket-image-source: setup/source-images/s3.md
  setup/adding-image-source: setup/source-images/domain.md
  setup/adding-http-image-source: setup/source-images/http.md